### ISSUE TITLE
Rotations stop being pure rotations. 

### ISSUE THREAD

**Issue by ChantalJuntao** [HolyLab/RegisterQD.jl#10]
So I've been finding this issue where when SD is anything but the identity matrix, the output rotation component isn't actually a pure rotation matrix even after stripping away the SD. 

It turns out this is because in line 4 of rigid.jl, the SD is changed to tform.linear\SD*tform.linear, which slightly warps the SD so that it no longer cancels out when composing the rigid and coarse transformations. 

Is there any reason we need to warp the SD? Can we just take this line out?

**Comment by Cody-G** [comment]
It may not be clear from the documentation (maybe we can clarify somewhere) but the output transformation isn't expected to be a pure rotation+shift when SD is anything other than the identity.  The transformation found by `qd_rigid` is the one that best aligns `moving` to `fixed` _including_ the spatial sampling directions/spacings respresented by the SD parameter.  So when SD is not the identity, the returned transformation is the composition of a rigid transformation and an initial transformation specified by SD.  Think of SD as setting the initial state for the optimization, and we're trying to find a rigid transformation from that initial state to the moving image.  When `initial_tfm` is provided (as we do in the fine registration step [here](https://github.com/HolyLab/RegisterQD.jl/blob/master/src/rigid.jl#L117)) we must account for any changes in directions/spacing induced by applying that initial transformation.  This is why we update SD to a new frame of reference before applying candidate transformations.

**Comment by timholy** [comment]
Sorry it has taken me a while to clear other things to get to this. Is there a reason we *can't* make it a pure rotation + shift? For example, we could change the algorithm to return the parameter of the rigid transformation, rather than the transformation itself. `SD` could always be used to change from array-coordinates to physical-coordinates.

**Comment by timholy** [comment]
To make the discussion a little more concrete, see #11.

**Comment by ChantalJuntao** [comment]
I think this issue pretty much counts as closed now?

**Comment by timholy** [comment]
Closed by #13 and #16
