### ISSUE TITLE
Removing QuadDIRECT part from RegisterOptimize

### ISSUE THREAD

**Issue by kdw503** [HolyLab/RegisterQD.jl#2]
@Cody-G 
Is this package a QuadDIRECT based registration separated from RegisterOptimize?
If so, can I remove qd_rigid.jl and related codes from the RegisterOptimize?

**Comment by Cody-G** [comment]
Yes it is, but I don't consider it finished until we can fix the major performance regression that I described in #1.  That regression seems unrelated to whether the code is here or in RegisterOptimize, but something changed in the transition from 0.6 to 0.7.  I haven't figured out whether this is an issue with QuadDIRECT itself.  Any ideas?

**Comment by kdw503** [comment]
Ok, I understand. But, I don't have any idea yet about the performance regression.
I will also look into this issue. And, I'll remove  QuadDIRECT parts from the RegisterOptimize.
