### ISSUE TITLE
qd_rigid failing in very simple cases

### ISSUE THREAD

**Issue by Nosferican** [HolyLab/RegisterQD.jl#25]
I am trying to use `qd_rigid` but it seems it is failing to detect simple cases.

For example,
```
fixed = reshape(1:9 .∈ Ref(1:2), 3, 3)
moving = reshape(1:9 .∈ Ref([5,8]), 3, 3)
qd = qd_rigid(fixed, moving, (3, 3), 3π/2)
[ qd[1](collect(elem.I)) for elem in findall(fixed) ]
```
vs
```
qd = qd_translate(fixed, rotr90(moving, 1), (3, 3))
sol = falses(3, 3)
for idx in (CartesianIndex(Tuple(convert.(Int, qd[1](collect(elem.I))))) for elem in findall(fixed))
    sol[idx] = true
end
rotr90(sol, -1) == moving
```

**Comment by Nosferican** [comment]
It seems like `fvalue = eps()` and such helps but I am still getting weird solutions with `qd_affine`, `qd_rigid`, and `qd_translate`... Will post more examples.

**Comment by timholy** [comment]
For your first example, check out the warped image:
```julia
julia> movingw = warp(moving, tform, axes(fixed))
3×3 Matrix{Float64}:
 NaN           NaN  NaN
   0.999966    NaN  NaN
   3.44506e-5  NaN  NaN
```
Believe it or not, this is success: `fixed` looks like this
```julia
julia> fixed
3×3 BitMatrix:
 1  0  0
 1  0  0
 0  0  0
```
and the mismatch is computed as the average of the non-NaN (the in-bounds) pixels. You can control this with the `thresh` parameter, but keep in mind that these toy problems where most of the "action" occurs at the boundary are not really typical image-registration scenarios.

**Comment by Nosferican** [comment]
The application I am trying it out for is matching Game of Life generations that have been hashed by the pairwise distances. Some games might have quite a bit of cells alive but others might be quite low. How can I use `thresh` or re-centering as a pre-conditioner to get better results?

**Comment by timholy** [comment]
Did you check the docs on `thresh`? You pass in the minimum sum-of-squared-intensity. It should reject solutions that are below this (unless it can't find a solution that satisfies your condition).

My guess is that before this will work well for your application, you're going to want to implement an array type with periodic boundary conditions and use it for `moving`.

**Comment by Nosferican** [comment]
I had hoped that passing a `CircularArray` would be sufficient for the warping but same behavior. I tried a few values for `thresh` but seems to give the same results so it might still be the warping issue. Could `dmax` or `ndmax` be used to specify that the rotation should only be at 90, 180, 270 degrees? Don't know if that might help narrow it down.

**Comment by timholy** [comment]
> but same behavior

Meaning, `warp` still gives `NaN`s? That's the thing to focus on: fix that problem, and the rest of your problems should go away. Anything else will be an ugly hack that you'll regret in the long term.

You may need to tackle that in ImageTransformations.

**Comment by timholy** [comment]
If you only have a couple of angles to try, why don't you just enumerate them all and test them manually?

**Comment by Nosferican** [comment]
Aye. I might try doing the `rotl90` / `permutedims` (6 scenarios) and for each one use `qd_translate` and test which transformation worked. Would the `warp` issue still affect cases with `qd_translate` cases?

**Comment by timholy** [comment]
Yes, it will.

In case you didn't discover this yourself (juliahub.com is your friend): https://github.com/ericphanson/ModularIndices.jl and https://github.com/JuliaArrays/FFTViews.jl. Neither is quite what you need but you could create an array type in a few lines of code that wraps all indices as `A[mod1(i, end)]` (or with `Mod`).

**Comment by timholy** [comment]
If you've never written an array type before, it's pretty straightforward: https://docs.julialang.org/en/v1/manual/interfaces/#man-interface-array. FFTViews would probably be a good model, you might need to change just a couple of lines. Or maybe you could just wrap your arrays as FFTViews directly?

**Comment by Nosferican** [comment]
https://github.com/Vexatos/CircularArrays.jl which is the one I have been using does exactly that... I will test it and report back.

**Comment by timholy** [comment]
I'm going to add "periodic boundary conditions" to its README to make it more discoverable.

**Comment by timholy** [comment]
This seems stale and unlikely to be a problem with this package.
