### ISSUE TITLE
Unsatisfiable requirements detected for package RegisterMismatchCuda

### ISSUE THREAD

**Issue by ChantalJuntao** [HolyLab/RegisterQD.jl#51]
add RegisterQD@v0.3.2
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package RegisterMismatchCuda [ee0d8d85]:
 RegisterMismatchCuda [ee0d8d85] log:
 ├─possible versions are: 0.1.0-0.3.2 or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions: 0.1.0-0.3.2
 │ └─ImageCore [a09fc81d] log:
 │   ├─possible versions are: 0.7.0-0.10.1 or uninstalled
 │   ├─restricted by compatibility requirements with Images [916415d5] to versions: [0.7.0-0.8.22, 0.9.3-0.10.1]
 │   │ └─Images [916415d5] log:
 │   │   ├─possible versions are: 0.17.3-0.26.0 or uninstalled
 │   │   ├─restricted to versions * by an explicit requirement, leaving only versions: 0.17.3-0.26.0
 │   │   └─restricted by compatibility requirements with ImageCore [a09fc81d] to versions: 0.26.0 or uninstalled, leaving only versions: 0.26.0
 │   │     └─ImageCore [a09fc81d] log: see above
 │   └─restricted by compatibility requirements with RegisterQD [ac24ea0c] to versions: 0.10.0-0.10.1
 │     └─RegisterQD [ac24ea0c] log:
 │       ├─possible versions are: 0.1.0-0.3.2 or uninstalled
 │       └─restricted to versions 0.3.2 by an explicit requirement, leaving only versions: 0.3.2
 └─restricted by compatibility requirements with CUDAdrv [c5f51814] to versions: 0.3.2 or uninstalled — no versions left
   └─CUDAdrv [c5f51814] log:
     ├─possible versions are: 0.8.0-6.3.0 or uninstalled
     └─restricted by julia compatibility requirements to versions: uninstalled

**Comment by timholy** [comment]
I don't have an NVIDIA card so I can't run the tests. Do you know how to bump dependencies? It's not very hard. I will attempt to fix it locally but there's a chance you'll have to intervene.

**Comment by timholy** [comment]
Potential fix in https://github.com/HolyLab/RegisterMismatchCuda.jl/pull/18. I won't merge it until I hear from you that it works.

**Comment by timholy** [comment]
Closed by https://github.com/HolyLab/RegisterMismatchCuda.jl/pull/18
